In [1]:
import pandas as pd
import numpy as np
from datetime import datetime


from debther_texts import *
import cluster_func_np
import cluster_func_c
import cluster_functions
from numba import jit, njit, vectorize

In [2]:
gang = debther_gangtok()#[0:10000]
pek = debther_peking()#[0:10000]
gang = cluster_functions.clean(gang,sep=['་',' ','\n'])
pek = cluster_functions.clean(pek,sep=['་',' ','\n'])

no characters to replace given.
['་', ' ', '\n']
no characters to replace given.
['་', ' ', '\n']

In [3]:
len(gang)

28316

In [4]:
a = datetime.now()
df_1 = cluster_func_np.find_cluster(gang,pek,10,'gang','pek')
b = datetime.now()
print(b-a)

0:02:19.158925

In [5]:
a = datetime.now()
df_2 = cluster_func_c.find_cluster(gang,pek,10,'gang','pek')
b = datetime.now()
print(b-a)

0:00:15.101311ed

C:\Users\rdeic\AppData\Local\Temp\ipykernel_9772\347814035.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_2 = cluster_func_c.find_cluster(gang,pek,10,'gang','pek')

In [6]:
a = datetime.now()
df_3 = cluster_functions.find_cluster(gang,pek,10,'gang','pek')
b = datetime.now()
print(b-a)

0:00:30.072177ed

In [7]:
print(df_1.shape)
print(df_2.shape)
print(df_3.shape)

(821, 6)
(821, 6)
(821, 6)

In [8]:
df_1.head(50)

    start_gang  end_gang  start_pek  end_pek  length  differenz
0         21.0      59.0        5.0     43.0    38.0      -16.0
1         60.0      90.0       44.0     74.0    30.0      -16.0
2         93.0     105.0       77.0     89.0    12.0      -16.0
3        109.0     133.0      103.0    127.0    24.0       -6.0
4        134.0     157.0      129.0    152.0    23.0       -5.0
5        163.0     174.0      158.0    169.0    11.0       -5.0
6        175.0     191.0      170.0    186.0    16.0       -5.0
7        202.0     212.0      198.0    208.0    10.0       -4.0
8        217.0     227.0      214.0    224.0    10.0       -3.0
9        284.0     305.0      281.0    302.0    21.0       -3.0
10       306.0     319.0      304.0    317.0    13.0       -2.0
11       321.0     347.0      320.0    346.0    26.0       -1.0
12       353.0     377.0      352.0    376.0    24.0       -1.0
13       404.0     417.0      402.0    415.0    13.0       -2.0
14       426.0     452.0      424.0    450.0    26.0       -2.0
15       477.0     496.0      476.0    495.0    19.0       -1.0
16       525.0     543.0      526.0    544.0    18.0        1.0
17       604.0     629.0      607.0    632.0    25.0        3.0
18       664.0     674.0      667.0    677.0    10.0        3.0
19       685.0     697.0      688.0    700.0    12.0        3.0
20       711.0     727.0      712.0    728.0    16.0        1.0
21       761.0     774.0      762.0    775.0    13.0        1.0
22       820.0     838.0      809.0    827.0    18.0      -11.0
23       885.0     935.0      875.0    925.0    50.0      -10.0
24       939.0     955.0      929.0    945.0    16.0      -10.0
25       957.0     969.0      947.0    959.0    12.0      -10.0
26       987.0    1007.0      975.0    995.0    20.0      -12.0
27      1016.0    1038.0     1003.0   1025.0    22.0      -13.0
28      1042.0    1053.0     1030.0   1041.0    11.0      -12.0
29      1056.0    1070.0     1049.0   1063.0    14.0       -7.0
30      1089.0    1101.0     1082.0   1094.0    12.0       -7.0
31      1130.0    1145.0     1120.0   1135.0    15.0      -10.0
32      1150.0    1176.0     1141.0   1167.0    26.0       -9.0
33      1199.0    1212.0     1189.0   1202.0    13.0      -10.0
34      1218.0    1236.0     1209.0   1227.0    18.0       -9.0
35      1237.0    1254.0     1228.0   1245.0    17.0       -9.0
36      1273.0    1298.0     1265.0   1290.0    25.0       -8.0
37      1300.0    1316.0     1292.0   1308.0    16.0       -8.0
38      1321.0    1338.0     1312.0   1329.0    17.0       -9.0
39      1396.0    1409.0     1389.0   1402.0    13.0       -7.0
40      1495.0    1514.0     1490.0   1509.0    19.0       -5.0
41      1554.0    1564.0     1571.0   1581.0    10.0       17.0
42      1579.0    1592.0     1598.0   1611.0    13.0       19.0
43      1593.0    1603.0     1612.0   1622.0    10.0       19.0
44      1609.0    1647.0     1629.0   1667.0    38.0       20.0
45      1667.0    1681.0     1687.0   1701.0    14.0       20.0
46      1691.0    1701.0     1711.0   1721.0    10.0       20.0
47      1707.0    1726.0     1725.0   1744.0    19.0       18.0
48      1727.0    1763.0     1745.0   1781.0    36.0       18.0
49      1764.0    1787.0     1782.0   1805.0    23.0       18.0

In [9]:
df_2.head(50)

    start_gang  end_gang  start_pek  end_pek  length  differenz
0           21        59          5       43      38        -16
1           60        90         44       74      30        -16
2           93       105         77       89      12        -16
3          109       133        103      127      24         -6
4          134       157        129      152      23         -5
5          163       174        158      169      11         -5
6          175       191        170      186      16         -5
7          202       212        198      208      10         -4
8          217       227        214      224      10         -3
9          284       305        281      302      21         -3
10         306       319        304      317      13         -2
11         321       347        320      346      26         -1
12         353       377        352      376      24         -1
13         404       417        402      415      13         -2
14         426       452        424      450      26         -2
15         477       496        476      495      19         -1
16         525       543        526      544      18          1
17         604       629        607      632      25          3
18         664       674        667      677      10          3
19         685       697        688      700      12          3
20         711       727        712      728      16          1
21         761       774        762      775      13          1
22         820       838        809      827      18        -11
23         885       935        875      925      50        -10
24         939       955        929      945      16        -10
25         957       969        947      959      12        -10
26         987      1007        975      995      20        -12
27        1016      1038       1003     1025      22        -13
28        1042      1053       1030     1041      11        -12
29        1056      1070       1049     1063      14         -7
30        1089      1101       1082     1094      12         -7
31        1130      1145       1120     1135      15        -10
32        1150      1176       1141     1167      26         -9
33        1199      1212       1189     1202      13        -10
34        1218      1236       1209     1227      18         -9
35        1237      1254       1228     1245      17         -9
36        1273      1298       1265     1290      25         -8
37        1300      1316       1292     1308      16         -8
38        1321      1338       1312     1329      17         -9
39        1396      1409       1389     1402      13         -7
40        1495      1514       1490     1509      19         -5
41        1554      1564       1571     1581      10         17
42        1579      1592       1598     1611      13         19
43        1593      1603       1612     1622      10         19
44        1609      1647       1629     1667      38         20
45        1667      1681       1687     1701      14         20
46        1691      1701       1711     1721      10         20
47        1707      1726       1725     1744      19         18
48        1727      1763       1745     1781      36         18
49        1764      1787       1782     1805      23         18

In [10]:
diff = df_1.merge(df_2, on=df_1.columns.tolist(),how='outer',indicator=True)

In [11]:
diff

     start_gang  end_gang  start_pek  end_pek  length  differenz _merge
0          21.0      59.0        5.0     43.0    38.0      -16.0   both
1          60.0      90.0       44.0     74.0    30.0      -16.0   both
2          93.0     105.0       77.0     89.0    12.0      -16.0   both
3         109.0     133.0      103.0    127.0    24.0       -6.0   both
4         134.0     157.0      129.0    152.0    23.0       -5.0   both
..          ...       ...        ...      ...     ...        ...    ...
816     27943.0   27953.0    51353.0  51363.0    10.0    23410.0   both
817     27962.0   27972.0    51373.0  51383.0    10.0    23411.0   both
818     27980.0   28008.0    51391.0  51419.0    28.0    23411.0   both
819     28009.0   28022.0    51420.0  51433.0    13.0    23411.0   both
820     28036.0   28058.0    51449.0  51471.0    22.0    23413.0   both

[821 rows x 7 columns]